name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v7
        with:
          file: docker/build.dockerfile
          push: false
          tags: turnertech/nmbs:latest
          target: nmbs-trixie
          build-args: |
            DEBIAN_RELEASE=trixie
